### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by Gerst20051** [wali-s/diffchecker-cli#14]
ReferenceError: Promise is not defined
    at authorization (/usr/local/lib/node_modules/diffchecker/dist/auth.js:29:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/diffchecker/dist/diffchecker.js:59:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

<img width="667" alt="screenshot 2016-02-08 11 52 27" src="https://cloud.githubusercontent.com/assets/235372/12892352/b2cbb706-ce59-11e5-9e98-4336770b481e.png">

**Comment by Gerst20051** [comment]
I've updated to the latest version of npm but still getting the same error.

**Comment by Gerst20051** [comment]
Apparently updating node is more confusing than i thought. Following this worked. http://stackoverflow.com/a/17096621/882371

**Comment by OKNoah** [comment]
@Gerst20051 glad it is working for you :)
